version: '3.8'
services:
  # Main Flask application for LAB environment (uses prebuilt image)
  selling-options-lab-app:
    image: ghcr.io/louwilcox-cloud/selling-options-lab:latest
    container_name: selling-options-lab-app
    command: python main.py    # ← FIXED: Run main.py instead of app.py
    expose:
      - "5000"
    ports:
      - "5082:5000"  # same as your current LAB mapping
    env_file:
      - .env         # provides FLASK_ENV, SECRET_KEY, DATABASE_URL, POLYGON_API_KEY
    # keep the existing PG_* too, in case the app reads them
    environment:
      - PGHOST=lab-db
      - PGDATABASE=selling_options_lab
      - PGUSER=postgres
      - PGPASSWORD=lab_password_2025
      - PGPORT=5432
      - FLASK_ENV=production
      - LAB_ENVIRONMENT=true
    depends_on:
      - lab-db
    volumes:
      - ./flask_session:/app/flask_session
    networks:
      - lab-network
    restart: unless-stopped

  # PostgreSQL Database for LAB (unchanged)
  lab-db:
    image: postgres:16
    container_name: selling-options-lab-db
    environment:
      - POSTGRES_DB=selling_options_lab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lab_password_2025
    volumes:
      - lab_postgres_data:/var/lib/postgresql/data
    networks:
      - lab-network
    restart: unless-stopped
    ports:
      - "5433:5432"

volumes:
  lab_postgres_data:

networks:
  lab-network:
    driver: bridge