version: '3.8'

services:
  # Main Flask application for LAB environment
  selling-options-lab-app:
    build: .
    container_name: selling-options-lab-app
    expose:
      - "5000"
    ports:
      - "5082:5000"  # Match your existing LAB port mapping
    environment:
      - DATABASE_URL=postgresql://postgres:lab_password_2025@lab-db:5432/selling_options_lab
      - FLASK_ENV=production
      - LAB_ENVIRONMENT=true
    depends_on:
      - lab-db
    volumes:
      - ./flask_session:/app/flask_session
    networks:
      - lab-network
    restart: unless-stopped

  # PostgreSQL Database for LAB
  lab-db:
    image: postgres:16
    container_name: selling-options-lab-db
    environment:
      - POSTGRES_DB=selling_options_lab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lab_password_2025
    volumes:
      - lab_postgres_data:/var/lib/postgresql/data
    networks:
      - lab-network
    restart: unless-stopped
    # Expose database port for management if needed
    ports:
      - "5433:5432"

volumes:
  lab_postgres_data:

networks:
  lab-network:
    driver: bridge